export const SET_COURSES = "MARKETPLACE/SET_COURSES"
export const SET_MODAL = "MARKETPLACE/SET_MODAL"
export const SET_PROFILE = "MARKETPLACE/SET_PROFILE"
export const SET_ENROLLMENTS = "MARKETPLACE/SET_ENROLLMENTS"